import { DateIdea } from './types';

export const DEFAULT_DATES: DateIdea[] = [
  {
    id: 'story-1',
    title: 'We started talking (12:00 - 13:00)',
    description:
      'This is where we began. Marko made the first move and caught Liv’s attention, and we opened the very first chapter of us.',
    season: 'summer',
    status: 'completed',
    eventType: 'milestone',
    address: 'Online',
    plannedFor: '2026-06-23',
    livNote: 'We noticed each other in a real way.',
    markoNote: 'I took the first step and I am so glad I did.',
  },
  {
    id: 'story-2',
    title: 'Our first call (17:00 - 18:00)',
    description:
      'Our first call happened here. Marko was nervous, and we both felt that this connection was real from the beginning.',
    season: 'summer',
    status: 'completed',
    eventType: 'milestone',
    address: 'Phone call',
    plannedFor: '2026-06-24',
    livNote: 'We settled into each other quickly.',
    markoNote: 'I was nervous, but I felt calm when we talked.',
  },
  {
    id: 'story-3',
    title: 'Coffee date + horror doll story (18:00 - 19:00)',
    description:
      'We met for coffee. Marko ordered a smoothie, and Liv told us the horror doll story that made this date unforgettable.',
    season: 'summer',
    status: 'completed',
    eventType: 'food',
    address: 'Coffee shop',
    plannedFor: '2026-06-26',
    livNote: 'We laughed and opened up more.',
    markoNote: 'The smoothie and conversation both hit perfectly.',
  },
  {
    id: 'story-4',
    title: 'Manhattan restaurant + cannoli + SIM4C (16:00 - 21:00)',
    description:
      'We went to a crowded restaurant in Manhattan, took the SIM4C, and Liv devoured a cannoli. Marko forgot his umbrella because he was so mesmerized by Liv.',
    season: 'summer',
    status: 'completed',
    eventType: 'adventure',
    address: 'Manhattan, New York, NY',
    plannedFor: '2026-07-09',
    livNote: 'The city energy and the cannoli were elite.',
    markoNote: 'I forgot the umbrella because I could not stop focusing on Liv.',
  },
  {
    id: 'story-5',
    title: 'Princeton visit + boundaries talk (16:30 - 21:00)',
    description:
      'We visited Princeton University. We wanted the Met at first, but we enjoyed the gardens and had a meaningful boundaries conversation. We also learned we do not love humidity.',
    season: 'summer',
    status: 'completed',
    eventType: 'learning',
    address: 'Princeton University, Princeton, NJ',
    plannedFor: '2026-07-13',
    livNote: 'The gardens were beautiful and worth it.',
    markoNote: 'I loved how clearly we communicated with each other.',
  },
  {
    id: 'story-6',
    title: 'La Tourette walk (19:30 - 21:00)',
    description:
      'We walked at La Tourette golf course. The heat was rough at first, but the walk became really romantic. We still laugh about the bug bites.',
    season: 'summer',
    status: 'completed',
    eventType: 'walk',
    address: 'La Tourette Golf Course, Staten Island, NY',
    plannedFor: '2026-07-14',
    livNote: 'Hot weather, sweet walk, and a memory we kept.',
    markoNote: 'It turned into one of our most romantic evenings.',
  },
  {
    id: 'story-7',
    title: 'Milk and Honey + blueberry smoothie (16:00 - 17:30)',
    description:
      'We went to Milk and Honey and split a blueberry smoothie. We talked about Liv’s hearing in one ear, flowers that complement Liv, and how forest green is Liv’s favorite color.',
    season: 'summer',
    status: 'completed',
    eventType: 'food',
    address: 'Milk and Honey, Staten Island, NY',
    plannedFor: '2026-07-18',
    livNote: 'Blueberry smoothie and sweet conversation.',
    markoNote: 'I learned details that help me love Liv better.',
  },
  {
    id: 'story-8',
    title: 'Leak scare before Bible study (20:00)',
    description:
      'On the way to Bible study, we had a leak scare moment and a rush of nerves. We pushed through uncertainty together while messages and timing felt intense.',
    season: 'summer',
    status: 'completed',
    eventType: 'faith',
    address: 'On the way to Bible study',
    plannedFor: '2026-07-18',
    livNote: 'Even stressful moments showed we are a team.',
    markoNote: 'I almost revealed everything because my feelings were so strong.',
  },
  {
    id: 'story-9',
    title: 'Time together (18:00 - 20:00)',
    description:
      'We spent intentional time together and kept building us. No big production, just us showing up for each other.',
    season: 'summer',
    status: 'completed',
    eventType: 'family',
    address: 'Staten Island, NY',
    plannedFor: '2026-07-19',
    livNote: 'Simple time together still means a lot.',
    markoNote: 'Being with Liv always feels worth it.',
  },
];
